### ISSUE TITLE
Improve performance when packages metadata is large.

### ISSUE THREAD

**Issue by vtsykun** [vtsykun/packeton#75]
- [x] Auto detect composer API user agent and disable `provider-includes` if composer = 2 (#76)
- [x] Using the redis storage to save last modified time by each packages (#76)
- [x]  Allow switch supported composer versions Composer1, Composer2. Allow to disable metadata v2 format   (#76)

Sometimes the first version of metadata format is faster than api v2 format. For example, in networks via http proxy, like tor or i2p composer can not use httpv2 to reuse connection, so 304 requests very slowly. So metadata v1 is better reuse cache due to sha256 hash identity.
